# Generated by Django 5.2.7 on 2025-10-23 23:32

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_name', models.CharField(max_length=120)),
                ('family_name', models.CharField(blank=True, max_length=120)),
                ('middle_names', models.CharField(blank=True, max_length=120)),
                ('suffix', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=20)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('birthplace', models.CharField(blank=True, max_length=200)),
                ('deathplace', models.CharField(blank=True, max_length=200)),
                ('photo_url', models.URLField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('location_text', models.CharField(blank=True, max_length=200)),
                ('custom_fields', models.JSONField(blank=True, default=dict)),
                ('is_living', models.BooleanField(default=True)),
                ('privacy_level', models.CharField(default='private', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_trees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('parent', 'parent'), ('child', 'child'), ('spouse', 'spouse'), ('ex_spouse', 'ex_spouse'), ('partner', 'partner'), ('sibling', 'sibling'), ('guardian', 'guardian'), ('adoptive_parent', 'adoptive_parent')], max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('certainty', models.FloatField(default=1.0)),
                ('from_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rels_from', to='trees.member')),
                ('to_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rels_to', to='trees.member')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='trees.tree')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='tree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trees.tree'),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('taken_at', models.DateField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, size=None)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='trees.member')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trees.tree')),
            ],
        ),
        migrations.CreateModel(
            name='TreeShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'owner'), ('editor', 'editor'), ('viewer', 'viewer')], max_length=10)),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='trees.tree')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tree_shares', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='member',
            index=django.contrib.postgres.indexes.GinIndex(fields=['custom_fields'], name='trees_membe_custom__78151d_gin'),
        ),
    ]
