# Generated by Django 5.2 on 2025-11-29 19:46

import Neetechs.settings.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DigitalProduct', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproduct',
            name='stripe_price_id',
            field=models.CharField(blank=True, help_text='Stripe Price ID for this product.', max_length=120),
        ),
        migrations.AlterField(
            model_name='digitalproductpurchase',
            name='stripe_payment_intent',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=120),
        ),
        migrations.CreateModel(
            name='DigitalProductBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('stripe_price_id', models.CharField(blank=True, help_text='Stripe Price ID for the whole bundle.', max_length=120)),
                ('thumbnail', models.ImageField(blank=True, null=True, storage=Neetechs.settings.storage.UploadsStorage(), upload_to='digital_products/bundles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(blank=True, related_name='bundles', to='DigitalProduct.digitalproduct')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DigitalProductBundlePurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stripe_payment_intent', models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=120)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DigitalProduct.digitalproductbundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'bundle')},
            },
        ),
    ]
