# Generated by Django 4.0.3 on 2022-10-13 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0006_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 21, 10, 20, 949811), null=True),
        ),
    ]
