# Generated by Django 5.2 on 2025-04-11 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0008_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 11, 9, 15, 39, 158002), null=True),
        ),
    ]
