# Generated by Django 5.2.7 on 2025-10-04 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0010_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='AboutSeller',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='About Seller'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='City/Municipality'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='country',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 3, 11, 50, 12, 932029), null=True),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='sellerName',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Seller Name'),
        ),
        migrations.AlterField(
            model_name='servicepost',
            name='state',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='State/County'),
        ),
    ]
