# Generated by Django 5.2.7 on 2025-10-04 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0011_alter_servicepost_aboutseller_alter_servicepost_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 11, 3, 11, 53, 53, 278821), null=True),
        ),
    ]
