# Generated by Django 5.2 on 2025-11-29 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0017_alter_servicepost_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepost',
            name='expiration_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 12, 29, 18, 44, 24, 848779), null=True),
        ),
    ]
