# Generated by Django 5.2 on 2025-05-12 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox_allauth', '0002_alter_customuser_first_name_alter_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
