# Generated by Django 5.2.7 on 2025-10-04 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knox_allauth', '0003_customuser_otp_created_at_customuser_phone_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Facebook_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='Linkdin_link',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='othersSocialMedia',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='stripeCustomerId',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='subscriptionType',
        ),
        migrations.AddField(
            model_name='customuser',
            name='linkedin_link',
            field=models.CharField(blank=True, help_text="User's LinkedIn profile link", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='other_social_media',
            field=models.CharField(blank=True, help_text="User's other social media link", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe Customer ID for billing', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_type',
            field=models.CharField(default='groundplan', max_length=20, verbose_name='Subscription type'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.TextField(default='The user did not put any thing yet', max_length=120, verbose_name='About me'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Municipality'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, help_text="User's Twitter profile link", max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='facebook_link',
            field=models.CharField(blank=True, help_text="User's Facebook profile link", max_length=120, null=True),
        ),
    ]
