name: Deploy Django to Linode

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "22" "${{ secrets.SSH_HOST_LINODE }}" >> ~/.ssh/known_hosts

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.SSH_HOST_LINODE }}
          username: ${{ secrets.SSH_USER_LINODE }}
          key: ${{ secrets.SSH_KEY_LINODE }}
          port: 22
          script_stop: true
          script: |
            set -e
            cd /srv/neetechs/app
            git pull --ff-only
            source /srv/neetechs/env/bin/activate || python3 -m venv /srv/neetechs/env && source /srv/neetechs/env/bin/activate
            pip install --upgrade pip wheel
            [ -f requirements.linux.txt ] && pip install -r requirements.linux.txt --upgrade
            set -a; source .env; set +a
            python manage.py migrate --noinput -v 2
            python manage.py collectstatic --noinput
            deactivate
            sudo systemctl restart gunicorn-neetechs
