name: Webhook Trigger to Django

on:
  push:
    branches: [ main ]

jobs:
  call-webhook:
    runs-on: ubuntu-latest

    steps:
      - name: Send POST request to Django Webhook
        run: |
          curl -X POST https://${{ secrets.DEPLOY_WEBHOOK_URL }} \
            -H "X-DEPLOY-SECRET: ${{ secrets.WEBHOOK_SECRET }}"
